[package]
name = "pprof"
version = "0.4.0"
authors = ["Yang Keao <keao.yang@yahoo.com>"]
edition = "2018"
license = "Apache-2.0"
description = "An internal perf tools for rust programs."
repository = "https://github.com/tikv/pprof-rs"
documentation = "https://docs.rs/pprof/"
readme = "README.md"

[features]
flamegraph = ["inferno"]
prost-protobuf = ["pprof-protobuf/prost-protobuf"]
rust-protobuf = ["pprof-protobuf/rust-protobuf"]

[dependencies]
backtrace = "0.3"
lazy_static = "1.4"
libc = "^0.2.66"
log = "0.4"
nix = "0.16"
rustc-demangle = "0.1"
spin = "0.5"
tempfile = "3.1"
thiserror = "1.0"

inferno = { version = "0.9", default-features = false, features = ["nameattr"], optional = true }

pprof-protobuf = {path = "./pprof_protobuf", optional = true}

[dev-dependencies]
rand = "0.7.2"

[workspace]
members = [
    "./pprof_protobuf"
]

[[example]]
name = "flamegraph"
required-features = ["flamegraph"]

[[example]]
name = "profile_prost"
required-features = ["prost-protobuf"]

[[example]]
name = "profile_rust_protobuf"
required-features = ["rust-protobuf"]

[[example]]
name = "multithread_flamegraph"
required-features = ["flamegraph"]

[package.metadata.docs.rs]
features = ["prost-protobuf"]
no-deps = true