on: [push, pull_request]

name: build

jobs:
  lint:
    name: Format and Clippy
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - name: Install Protoc
        uses: YangKeao/setup-protoc@master
        with:
          version: '3.11.4'

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Run cargo clippy - flamegraph
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --features flamegraph -- -D warnings

      - name: Run cargo clippy - prost-protobuf
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --features prost-protobuf -- -D warnings

      - name: Run cargo clippy - rust-protobuf
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --features rust-protobuf -- -D warnings

  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install Rust nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - name: Install Protoc
        uses: YangKeao/setup-protoc@master
        with:
          version: '3.11.4'

      - name: Run cargo test - flamegraph
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features flamegraph

      - name: Run cargo test - prost-protobuf
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features prost-protobuf

      - name: Run cargo test - rust-protobuf
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features rust-protobuf