on: [push, pull_request]

name: build

jobs:
  lint:
    name: Format and Clippy
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Run cargo clippy - flamegraph
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --features flamegraph -- -D warnings

      - name: Run cargo clippy - prost-codec
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --features prost-codec -- -D warnings

      - name: Run cargo clippy - protobuf-codec
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --features protobuf-codec -- -D warnings

  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install Rust nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - name: Run cargo test - flamegraph
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features flamegraph

      - name: Run cargo test - prost-codec
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features prost-codec

      - name: Run cargo test - protobuf-codec
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features protobuf-codec
